### ISSUE TITLE
Not able to draw the polyline in the viewdidappear. 

### ISSUE THREAD

**Issue by pratyush0211** [dylanmaryk/DottedPolyline#1]
Hi,

I am unable to draw the polyline in the viewdidappear. The screen launches with animation of the map due to which the circle size is more than the needed size. Is there any way to fix this? The polyine works fine when using did change state but the map zoom is frozen in this case.

Could you please help me out with this?

**Comment by dylanmaryk** [comment]
I'm struggling to visualise the problem. Could you please send me some screenshots of what you see?

**Comment by pratyush0211** [comment]
I have fixed the issue. Thanks. Appreciate this piece of gem! Worked like a charm
